name: Build and push docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Docker tags
        id: tags
        run: |
          TAGS="ghcr.io/pbdas/epa-ng:${{ github.event.release.tag_name }}"
          if [[ "${{ github.event.release.prerelease }}" != "true" ]]; then
            TAGS="${TAGS}"$'\n'"ghcr.io/pbdas/epa-ng:latest"
          fi
          echo "value<<EOF" >> $GITHUB_OUTPUT
          echo "$TAGS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.value }}

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run placement test
        run: |
          mkdir epa_out
          docker run --rm \
            -v ${{ github.workspace }}/test/data:/data \
            -v ${{ github.workspace }}/epa_out:/out \
            ghcr.io/pbdas/epa-ng:${{ github.event.release.tag_name }} \
            epa-ng --tree /data/ref.tre --ref-msa /data/aln.fasta --query /data/query.fasta --outdir /out
      - name: Check output
        run: test -f epa_out/epa_result.jplace
