name: build&test_macos

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: get dependencies
        run: |
          brew install libomp bison
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
      - name: make epa
        run: make -j
      - name: run tests
        run: ./test/bin/epa_test
